[build]
  command = "npm run build"
  publish = "dist"

# Admin SPA
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# La Netlify endepunkter fungere
[[redirects]]
  from = "/.netlify/*"
  to = "/.netlify/:splat"
  status = 200
